version: '3.7'
services:
  api:
    build: .
    depends_on:
      - mongo
    ports:
      - "${HTTP4S_PORT:-80}:8080"
    networks:
      - frontend
      - backend
  mongo:
    image: mongo:4.2
    networks:
      - backend

networks:
  frontend:
  backend:
